### ISSUE TITLE
where to you place "set_papertrail_user(user)"?

### ISSUE THREAD

**Issue by jcavalieri** [sardaukar/grape-papertrail#2]
Thanks for writing this gem. It is exactly what I need. However I'm confused by the documentation. Where do you place "set_papertrail_user(user)"?

Could you stick an example that includes what file you put this in?

Thanks,
John

**Comment by sardaukar** [comment]
Here: https://github.com/sardaukar/grape-papertrail/blob/master/lib/grape/papertrail.rb

You could also have used the search box at the top of the page, to the right of the Github logo.

**Comment by jcavalieri** [comment]
Sorry for the confusion, I meant where do you call that method not where is it declared.

Regardless, I found that all I needed to do was assign whodunnit in grape api's before event.

```
  before do
    error!('Unauthorized', 401) unless authenticate!(env, logger)

    if @api_key
      ::PaperTrail.whodunnit = @api_key.client_name
    end
  end
```
